### ISSUE TITLE
Discovering if an entity element is updatable

### ISSUE THREAD

**Issue by neilstevens2005** [anthonywhitford/bic-lcf#10]
Currently there is nothing in LCF entities indicating if an element of an entity is updatable.  In an ideal world all elements of all entities will be editable, however in practice different LMS vendors store different data which will therefore be mapped to the LCF entities differently.  (For example one LMS vendor may support notes on loans while another may not).  Not allowing a client to know what is uneditable is likely to result in problems.  For example imagine if an LCF implementation does not support updating borrowers address (via a POST to the Contact entity), and a very clever self service machine (or other client) connected attempts to do this.  It would be very frustrating for the end user to type in their new address only to be informed that the address could not be updated afterwards.

Therefore I think it would be beneficial to add an "updatable" (and possibly "deleteable") attribute to each XML element indicating if clients are able to update (or delete) the element.  This solution does not fully address the problem of clients sending updates which can not carried out on the underlying LMS, but I would expect it would prevent the majority of unsupported entity update requests.  It would still be a problem where for example an LMS supported mobile phone numbers (CMT code 04), but not work phone numbers (CMT code 03) and client attempted to add a work number.

Another similar idea I had was elements with a 1-n cardinality could also have an optional max-size attribute.  For example some LMS implementations may support a loan having no notes, a single note, or an unlimited number of notes.  On implementations which support up to one note per loan the "notes" element could contain the attribute "max-size="1"".

**Comment by franciscave** [comment]
These are interesting suggestions. They raise the question of the degree to which we are aiming to achieve full interoperability, or the extent to which it should be possible to determine which features are supported by a particular implementation and which are not. Again, this requires further discussion, but in principle I like the idea of adding attributes. I think we should also look at adding some exception conditions to code list EXC to make it possible to respond that a request has tried to request an unsupported action such as updated a non-updatable element or adding a repeatable element that exceeds the maximum number of supported repeats (which may be '1').

**Comment by franciscave** [comment]
I will draft documentation changes to make clear that certain fields are read-only and must be ignored when entities are either created or modified.

**Comment by franciscave** [comment]
In the LCF v1.0 specification I have added a new note [5] at the end and I have added an 'R' suffix to the cardinalities of the following elements of a Manifestation entity: E01D15, E01D18, E01D19 and E01D20. I hesitated about also flagging E01D16 and E01D17 as read/response only. Once we've agreed on which elements to flag in E01, I'll apply the same principles to the other entities.

**Comment by franciscave** [comment]
The new note is in fact note [6] in the LCF v1.0.1 spec, and I've added the same note [1] to the entity XML binding spec. I've now added 'R' following the cardinality of each entity element that I think is in the read/response-only category. Please review both specs.
