### ISSUE TITLE
Schema Review Prior to 1.0.1 issue

### ISSUE THREAD

**Issue by mdovey** [anthonywhitford/bic-lcf#110]
REST response schema still have version attribute
LOT code table missing item LOT04
Tidy up of embedded documentation
Code lists in rest response schema rather than code lists schema
NOT type enumeration is 00 rather than 01
IMT missing from schema (although not directly referenced it would be of value see issue #70)
loan-characteristic element and loanCharacteristicType enumeration are not used
feeOrFineType enumeration is not used
Need to extract ONIX codelist contributor role into dedicated onix codelist file
Update contributor role values from latest ONIX lists

**Comment by mdovey** [comment]
There are two enumerations - loanCharacteristic and feeOrFine - which appear to be surplus to requirements (they aren't used anywhere in the schema) and which don't correspond to any codelist.

I suspect that these might be artefacts from earlier drafts which didn't get properly deleted but I'd like to confirm this before removing them.

**Comment by franciscave** [comment]
The enumeration loanCharacteristic used to relate to element loan-characteristic in E02 Item, but this was dropped from LCF v1.0 in November 2013, so it is a historical artefact can safely be removed.

The enumeration feeOrFine is was used by the element fee-type within fee-limit, but the element fee-type was replaced sometime in 2013 by charge-type, so this is also redundant and can safely be removed.
