### ISSUE TITLE
Queries related to codelists not included in REST implementation

### ISSUE THREAD

**Issue by mdovey** [anthonywhitford/bic-lcf#112]
In reviewing the xml schemas prior to finalising 1.0.1, I note there are a number of codelists not in the schemas.

Some of these are not relevant to the REST implementation, however, they do suggest some additional functionality not currently implemented in the REST implementation which we might was to review and add to a future version (e.g. quotations already targeted by issue #84, indicating third-party\patron not present operations, partial record retrieval, etc.)

However, there are also a few which appear to be orphans. 

Details below.

| Codelist ID  | Codelist   | Comment |
| - | - | - |
| ALF | Allow Fees Flag | I can't find this referenced in either the XML binding, REST specification or the data framework |
| DTM | Date or Date-time Format | I can't find this referenced in either the XML binding, REST specification or the data framework |
| ECR | Encryption algorithm | Not applicable to REST, as we use mechanisms in HTTP e.g. HTTPS and HTTP authentication |
| IMD | Item detailed information type | This appears to be part of a mechanism for requesting partial records. I can't see this refered to in the REST specification, or any alternative partial record request mechanism. Was it decided this feature was not needed in REST, or is this on the back burner (in which case we should create an issue even if scheduled for someday) |
| MND | Manifestation detailed information type | This appears to be part of a mechanism for requesting partial records. I can't see this refered to in the REST specification, or any alternative partial record request mechanism. Was it decided this feature was not needed in REST, or is this on the back burner (in which case we should create an issue even if scheduled for someday) |
| MOT | Entity modification type | Not applicable to REST as we map onto the HTTP actions |
| PNT | Patron detailed information type | This appears to be part of a mechanism for requesting partial records. I can't see this refered to in the REST specification, or any alternative partial record request mechanism. Was it decided this feature was not needed in REST, or is this on the back burner (in which case we should create an issue even if scheduled for someday) |
| RNQ | Renewal Request Type | I presume that this is in general not applicable to REST, however there is functionality here which does not currently appear to be available in the REST interface - such as third party renewals. I'm also not sure why this is not merged into the general RQT request type e.g. third party (patron not present) might be a useful flag for all operations not just renewals. We have opened an issue to look at quotations in 1.0.2 |
| RQT | Request type | Not applicable to REST but we have opened an issue to look at quotations in 1.0.2 |
| RST | Response type | Not applicable to REST |
| RVQ | Reservation request type | I'm not sure why this is not merged into RQT given the substantial overlap. Not applicable to REST but we have opened an issue to look at quotations in 1.0.2 |

**Comment by franciscave** [comment]
IMD, MND and PNT are all used by Q02D03, which as I recall we decided not to implement in the REST web service implementation.

**Comment by franciscave** [comment]
ALF appears to be completely redundant, as I cannot find any use in earlier LCF drafts or in v1.0. I'll remove it.

DTM was used in LCF v1.0 to enable the date-time format to be specified in requests and responses. We dropped this at some point, so the code list is unused. I think we could safely leave it in.

**Comment by franciscave** [comment]
All the other code lists you mention can be kept for potential use by future implementations that don't use REST or web services.

**Comment by mdovey** [comment]
I'm closing this in preference to the following issues:

Issue #115 (partial record return)
Issue #116 (third party\patron not present requests)
Issue #117 (renew all)
Issue #118 (Do we really need seperate code lists for RVQ, RQT, and RNQ)
