### ISSUE TITLE
Communication locator might not always be a single string

### ISSUE THREAD

**Issue by franciscave** [anthonywhitford/bic-lcf#12]
In folding Contact properties back into the Patron entity it probably makes sense for a Patron address to become simply another instances of Communication Details (currently E09C05), in which case Communication Locator (currently E09D05.2) would need to contain multiple address lines. This suggests that Communication Locator should become a composite property containing 1-n Communication Locator Line properties. We would need to provide some guidance on how to use this, since Locator Lines make sense for some Communication Types but not for others.

**Comment by franciscave** [comment]
Communication Locator Lines might benefit from being typed. This suggests that we might introduce an altermative composite Communication Locator Part, with sub-elements Type and Value. Types would ideally be from a code list, which could include address components (e.g. Building Name/Number, Street, Town, Post Code).

**Comment by franciscave** [comment]
I think best would be to have a choice between 'locator' as we now have it, i.e. repeatable but just a series of un-typed strings, and a single new element 'structured-locator' contain one or more 'locator-part' elements, each 'locator-part' containing a 'type' and a 'value' element. The values of type that would make sense would depend upon 'communication-type', e.g. there would be different choices of types for postal addresses, for email addresses, for phone numbers. Would this be over the top?

**Comment by anthonywhitford** [comment]
Decision on the LCF Technical Panel call was that for now, we use the existing model, with multiple lines for any locator type as required. If we require structure within the data, then we investigate the use of vCard, thus adopting that standard and avoiding redesigning something that already exists.
