### ISSUE TITLE
Encryption

### ISSUE THREAD

**Issue by franciscave** [anthonywhitford/bic-lcf#14]
We need to make it clear in the web service implementation documentation that, because LCF communication may contain personal data, communication must/should (which?) be encrypted. The place for this is probably in the implementation notes.

**Comment by mdovey** [comment]
Yes, I would suggest that the in production, webservices should be over https, unless the specific application is assured of a secure\private network (e.g. VPN).  (http might be used for development purposes).

**Comment by franciscave** [comment]
Please check new text forming a new item 3 under the heading 'Implementation notes' in the web service implementation documentation [here](https://github.com/anthonywhitford/bic-lcf/wiki/LCF-1.0-REST-Web-Service-Specification).

**Comment by anthonywhitford** [comment]
"Connections should use HTTPS for all Live deployments"

**Comment by franciscave** [comment]
I've changed the text in the web services implementation spec.
