### ISSUE TITLE
Datatype for code lists in entities XML schema

### ISSUE THREAD

**Issue by franciscave** [anthonywhitford/bic-lcf#16]
The use of xs:token as the base datatype for most of the LCF code lists in the entities XML schema means that XML parsers will ignore white space around code values in the affected elements. For interoperability it would probably be better if the base datatype were xs:string, as parsers will then not ignore white space and this reduces the scope for variation among implementations.

**Comment by anthonywhitford** [comment]
Interesting. For the same reasons as you, I'd choose xs:token.

**Comment by franciscave** [comment]
It seems that one can argue this either way. xs:string is the better choice if the server is expecting the client to have parsed and normalised the XML data before submitting it. xs:token would arguably be the better choice if the server expects to parse and normalise everything on receipt, allowing more flexibility for clients.

**Comment by anthonywhitford** [comment]
Agreed on the conference call that we would use xs:string

**Comment by anthonywhitford** [comment]
Schema amended in revision: https://github.com/anthonywhitford/bic-lcf/commit/466c2f9673d32e398fd613d207de008c0da24844

**Comment by anthonywhitford** [comment]
@franciscave - Could you close this issue when you've updated the wiki?

**Comment by franciscave** [comment]
I propose that in the entity XML binding specification we should replace the datatypes 'String', 'Integer', 'Decimal' and 'DateTime' with the XSD datatypes 'string', 'int', 'decimal' and 'dateTime' respectively. I think that is the only documentation change that is necessary.

**Comment by franciscave** [comment]
Now done in the information entity XML binding and web service documentation.

**Comment by mdovey** [comment]
chargeStatus still has xs:token as base type
