### ISSUE TITLE
Authentication & Access Logs

### ISSUE THREAD

**Issue by anthonywhitford** [anthonywhitford/bic-lcf#19]
When we're looking to use a Patron's barcode and PIN within a web service call, the LCF standard currently mandates that these values should be passed on the query string to the request. This would be insecure, since the query string will be recorded in plain text in access logs throughout the proxies and servers before the service is processed. In effect this means that the Barcode and PIN would be captured in a file in plain text, which is a violation of OWASP guidelines. 

We need to ensure that these details are only ever passed within the body of the request, typically as FORM POST parameters, or we find an alternative machanism completely.

**Comment by franciscave** [comment]
I think what you're saying is that, if patron authentication is required, all requests must be HTTP POSTs containing the patron authentication in the resource being POSTed. If so, we'll need to revise the documentation for each request to specify both GET (no patron authentication required) and POST (patron authentication required). I assume that the other parameters would remain the same and wouldn't be moved into the POSTed resource.

**Comment by anthonywhitford** [comment]
Hi Francis, 
It's not as simple as that, since that would be a violation of REST. The issue is that the HTTP verb carries meaning for the REST implementation, so your interpretation of making everything an HTTP POST where authentication is needed is a mis-use of the POST, since POST means create. 

This leaves us with a challenge. We *could* make use of the HTTP/1.1 specification ambiguity, that allows a GET request to be supplied with a BODY. However this would be a violation of the sematics of a GET request, since HTTP/1.1 infers that while the body may be present, it should have no effect on the response from the server. In effect, pass what you like in a GET request body and it should be ignored. 

This means we're then looking at out of band data, such as HTTP Headers. We could use headers to pass this extra request context and according to the standards this would be ok. This may also be a good opportunity to think about OAUTH, since that's the mechanism that it uses to pass the authenticated token around. 

The only other thing to consider, is whether the only places where Patron BARCODE/PIN is required happen to already be POST/PUT requests. If they are and we can guarantee that there would never be a GET requiring these secondary credentials, we might look to add them to the entity iteself as a write only element. I think that the only scenario where we need both Barcode and PIN might be where we are looking to identify the Patron, something akin to an authentication request. Would you be able to check whether this is the case?

**Comment by franciscave** [comment]
Some history: the reason that LCF includes username (barcode) and password (PIN) is that LCF was originally based upon SIP2, and SIP2 includes user authentication fields CN (user ID) and CO (password). 

If you look at the LCF v1.0.1 specification, and specifically at elements common to all requests in table Q00, you’ll see that both user and terminal authentication elements are included, but the composites that contain them (Q00C01 and Q00C02) are both optional. You’ll see that there is also a note that these elements would not normally be handled as part of the request message payload but at a “…different level in the messaging protocol stack (e.g. in HTTP or SSL)…”.

As far as I can remember, or can find in the spec, LCF v1.0.1 is entirely silent about when user authentication should be included in a request. The only other place where user authentication is mentioned is in Implementation Note 2 in the LCF 1.0.1 REST Web Service Specification. [In passing, I’ve noticed an error in this note, in that it mentions Q00C02, but this is for terminal authentication, not user authentication.]

If LCF is silent about when user authentication is needed, we probably need to ask the Technical Panel for their view on this. My (layman’s) view on this would be that user authentication must certainly be required for creating or modifying records, but that there are probably some kinds of record retrieval which would also require it, i.e. retrieval of any records that would allow the user to view personal data relating to a patron – this should require user authentication, I think. If user authentication is required for some GET requests, and I think it probably is, a payload-based solution to user authentication isn't going to be sufficient.

Regardless of which requests need user authentication, we need to find a technical solution that doesn’t violate REST principles (very much a case of trying to reconcile openness with privacy, so it’s a compromise whichever way you do it!). If OAuth is the way to go, let’s investigate that more thoroughly.

**Comment by franciscave** [comment]
I think that this issue can now be subsumed into #24.
