### ISSUE TITLE
OAuth for authentication of terminal applications

### ISSUE THREAD

**Issue by anthonywhitford** [anthonywhitford/bic-lcf#2]
We currently recommend the use of HTTP challenge response, IP restriction or PKI authentication for terminal applications wishing to use LCF services. We should include OAuth (oauth.net) as a web authentication standard.

**Comment by franciscave** [comment]
We should discuss this with the Technical Panel in due course.

**Comment by franciscave** [comment]
I think that this issue is now covered by #24.
