### ISSUE TITLE
Providing entity identifiers upon creation

### ISSUE THREAD

**Issue by neilstevens2005** [anthonywhitford/bic-lcf#20]
The LCF specification does not specify which of the following is true when creating a new entity via a HTTP POST request:

 a) The client should never provide an entity's identifier, as all entity identifiers should be generated by the server. Or:
 b) The client should always provide an entity's identifier, and the server will then be forced to use this identifier. Or:
 c) The client should provide an identifier when creating certain entities, but not provide an identifier when creating others.
 
I would assume point c above is true, but I am worried it will cause interoperability problems if not specified in detail, since LMS vendors may assume different entities should have their identifiers generated by the client.

I think entity identifiers should always be generated on the server side, except in the case of an Item entity or a Patron entity (since I am assuming the patron and item identifier will always be their barcodes as is the case in SIP).  The reasons for allowing the client to specify the identifier is it would be useful if the LCF could be used in the following scenarios:

 - An item which has already has been barcoded is being added to library via an LCF client , therefore it is important that the LCF client can specify the barcode on creation.
 - A member of Library staff is using an LCF client to add a borrower.  The staff member might take the next free library card out a drawer or cupboard and assign it to the borrower.
 
Therefore it is essential that LCF servers allow clients to specify the patron and item identifiers.  However the scenario may also take place where a new patron is using an LCF client (imagine this is a page on the library website) to join the library.  In this case the library might post the patrons library card to them through the mail, in which case the LCF server would need to generate the patron barcode itself.  Therefore maybe LCF servers should be able to generate a patron barcode if not specified by the client.

I am asking this question in the hope it will provoke discussion.  I think the simplest solution to allow all implementations to be interoperable would be for LCF servers to allow clients to specify identifiers for both Patron and Item entities, but not require them to do so, as well as agreeing that the LCF server will be responsible for generating identifiers on all other entities.

**Comment by franciscave** [comment]
I agree. In fact, I would probably go further and say that if a client specifies an identifier in the XML payload when creating or modifying an entity of any kind, the server should ignore it and assign its own identifier. I think we need to flag entity identifiers as "read-only", which means that they are mandatory in responses but are not allowed in the XML payload in entity creation or modification requests.

**Comment by franciscave** [comment]
I have added a new element 'Barcode identifier' to the Patron entity, and I have also added an 'Additional identifier' composite, reflecting that we have this in other entities (Manifestation, Item, Location) that might have multiple forms of identification. I have also adjusted Note [4] at the end of the LCF v1.0.1 specification to clarify that the Identifier element (i.e. the LMS-assigned identifier) is not mandatory when creating a new entity and may be ignored by the LMS if specified in a Create entity request. So far I have only edited the LCF v1.0.1 specification and not the XML binding - that comes next. Please review and comment.

**Comment by franciscave** [comment]
I think we can close this issue at the next Technical Panel meeting.

**Comment by franciscave** [comment]
At the Technical Panel meeting on 28 June it was agreed that the changes are satisfactory. The XML schema should be changed to allow the identifier to be omitted when creating a new instance of an entity.

**Comment by anthonywhitford** [comment]
Amended lcf-v1.0-entities.xsd to make all references to the "identifier" element minOccurs=0, and amended the comment to instruct that this element should not be populated when the entity is being created.

**Comment by anthonywhitford** [comment]
Pull request created and assigned to @mdovey and @franciscave for approval.

**Comment by anthonywhitford** [comment]
Pull request approved by Francis. Closing.
