### ISSUE TITLE
"As a self service device developer I need to be able to determine the age of a patron."

### ISSUE THREAD

**Issue by MarkOliver** [anthonywhitford/bic-lcf#25]
"As a self service device developer I need to be able to determine the age of a patron."

We will process a patron according to their age, or borrower category, so that children, teens and adults can be handled differently.  At present the standard doesn't appear to offer this.

It is something that various flavours of SIP2 have offered and handled in different ways, so this has been a requirement of other systems in the past.

**Comment by anthonywhitford** [comment]
Hi Mark, 

Thanks for the question. I'm wondering though whether this is correctly the resposibility of the self-service machine? Is the decision of whether to issue something to a Patron governed by business rules within the LMS/ILS? For example, if an attempt were made to issue an 18 rated DVD to a minor this should be blocked, however the LMS will have the knowledge of how the Patron has been modelled, and therefore whether this is based on accudate date of birth information, categorisation by Patron type etc. 

In which scnearios should this decision be made by the self-service machine?

**Comment by MarkOliver** [comment]
Our system "issues" its own things that the LMS is not aware of.

One particular example in more detail...

This is a PC booking solution, when a patron logs into a PC they do so using their library card.  Different types of patrons have different restrictions placed upon them.  So we need to put patrons into particular groups based upon their date of birth, and those groups then give them the restrictions that they need.

We make a call to the LMS to verify the patron and their PIN and then grab their details, and we use rules based upon those details to decide on the group that a patron should be in.

The SIP2 systems that we interface with tend to give us back date of birth in a variety of ways as a part of the 64 response (for example sometimes it's PB).

**Comment by franciscave** [comment]
I've just checked my SIP2 documentation and cannot find any field for communicating the age of a patron. Was this in a SIP2 extension? My reason for asking is that LCF is supposed to cover all SIP2 fields that are being used currently.

**Comment by MarkOliver** [comment]
Date of birth is something that's in various implementations of SIP2, I don't believe that it's a part of the core standard.

It looks like a number of providers agreed upon PB, but even then we get it in different formats.  Other providers use other fields, and formats, entirely.

All of this is talking about the 64 response.

**Comment by anthonywhitford** [comment]
I'm pro adding in date of birth for a patron, since all customer joining
forms request this for my customers. It is not mandatory as a field, since
they may decline to provide it, but library policy usually states it must
be provided.

If we add it to the patron entity as "date-of-birth", type xs:date and
optional, that's fine with me.

**Comment by franciscave** [comment]
OK, if you update the schema, I'll make the necessary changes to the documentation

**Comment by anthonywhitford** [comment]
XML Schema updated.

**Comment by MarkOliver** [comment]
Thanks.

**Comment by franciscave** [comment]
Documentation changes have been made.
