### ISSUE TITLE
REST responses schema does not define elements 'reason-denied' and 'element-ref'.

### ISSUE THREAD

**Issue by franciscave** [anthonywhitford/bic-lcf#26]
When the response is to report an exception condition, an XML payload providing details of the exception condition may be included in the response. This would use the element **lcf-exception**, defined in the schema *lcf-v1.0-rest-responses.xsd*. However, two elements that are used in exception condition responses are not fully defined: **reason-denied** and **element-ref**. The former should use the code list RDN. The latter should be a string.

**Comment by mdovey** [comment]
Updated schema to correct this
