### ISSUE TITLE
Is E11 class-code or class-term

### ISSUE THREAD

**Issue by mdovey** [anthonywhitford/bic-lcf#27]
E11 is called class code in the main document, and also class-code in the ENT code list so for the web service access is via the URL /lcf/1.0/class-code

However, E11 is called class-term in the XML schema document and the XSD.

For all other entities the ENT code and schema name is consistent (modulo punctuation characters).

**Comment by anthonywhitford** [comment]
Sounds like a typo to me. Want to fix it?

**Comment by mdovey** [comment]
Any preference which one it should be?

**Comment by anthonywhitford** [comment]
I'd go with class-code, in line with the previously circulated
documentation.

Any preference which one it should be?

—
Reply to this email directly or view it on GitHub
<https://github.com/anthonywhitford/bic-lcf/issues/27#issuecomment-172244485>
.

**Comment by mdovey** [comment]
ah, I see the problem. The entity class-code contains an sub-element called class-code - because the XSD uses the style of defining types by reference to top level elements, this causes a name clash.

As I see it there are four solutions:

i) leave as is - I don't like this as anyone reading the schema may not realise that class-term is the same as class-code in the main documentation

ii) call the sub-element class-code-value - a bit of a kludge but the least disruptive

iii) inline the type of the sub-element e.g.

		<xs:element name="class-code" type="nonEmptyString"/>
instead of 
                 <xs:element ref="class-code"/>

which is pretty effective but violates the style used elsewhere in the xsd

iv) keep the nomenclature of the XML schema and update the other documentation to match

**Comment by franciscave** [comment]
My preference would be as follows: 

The headings for entity E11 in the LCF v1.0.1 spec and the LCF v1.0.1 entity XML binding spec should be aligned as 'E11 TITLE CLASSIFICATION TERM'.

The description of entity E11 in the LCF v1.0.1 spec should be corrected to read "A classification term within an identified classification scheme for classification of titles." A bit verbose, but unambiguous.

The XML binding for E11D02 should be changed from 'code' to 'class-code' to align with the XSD.

The definition of the element 'class-code' in the XSD should have type="nonEmptyString" added as suggested by Matthew.

I'll make the documentation changes if Matthew or Anthony could adjust the XSD.

**Comment by franciscave** [comment]
One further change: in code list ENT we should change 'class-codes' to 'class-terms'.
