### ISSUE TITLE
Numeric entity codes values versus alpha values in lcf-entity-list-response

### ISSUE THREAD

**Issue by mdovey** [anthonywhitford/bic-lcf#28]
As far as I can tell the only place the numeric code values for ENT code is used is in the entity-type element of the lcf-entity-list-response (as the REST urls use plural versions of the alpha values).

For consistency, would it be better to specify that the entity-type used the alpha value?

If we do use the alpha value should this be the singular or plural form?

(I'm loath to suggest implementations can use either as this added additional complexity)

**Comment by anthonywhitford** [comment]
I agree that would make the REST api more intuitive.  +1

**Comment by franciscave** [comment]
I agree with this. I've added a clarification to the LCF REST Web Service spec.

**Comment by mdovey** [comment]
OK, what I've done in my copy of the XSD is to

rename the xs:enumeration entityType to entityTypeNumeric
created a new xs:enumeration called entityTypeAlpha

changed the type of entity-type under lcf-entity-list-response and entity-type under property to entityTypeAlpha.

I'll push this change if you are happy with this.

p.s. was the dropping of ENT12 from the 1.0.1 code list and also the schema enumerations intentional?

**Comment by anthonywhitford** [comment]
Why leave both enumerations in place? (both alpha and numeric ones). Isn't
that redundant now?

**Comment by mdovey** [comment]
Yep, you're right.

so schema will have xs:enumeration entityType using the alpha values (which is used by lcf-entity-list-response and property)

**Comment by mdovey** [comment]
New xml schema pushed

**Comment by franciscave** [comment]
The dropping of ENT12 from the code list was done provisionally on the basis of earlier discussion in which we appeared to be concluding that entity E12 Selection Criterion would not in practice be used. However, E12 remains in all the other documentation, so either we need to reinstate ENT12 or remove E12 from all documentation. I think there's an open issue already on this, but will re-open if necessary.
