### ISSUE TITLE
Are any of the repeatable elements of LCF 'flagable' as PRIME

### ISSUE THREAD

**Issue by mrgumby** [anthonywhitford/bic-lcf#34]
The recent plugfest was an absolute delight.  The organisers got it absolutely right: right size, right place, right content.  Thank you.

HOWEVER a spark is now growing into a bit of a burning issue:

A BORROWER may have a number of repeatable elements: Contact and Email Address to name but two.

Where does the responsibility lie to designate which of any repeated elements is prime so that (for example) self-service doesn't have to take on the unenviable and ergonomically poor task of asking a user to choose between alternatives, for example when choosing to receive receipts via email?

I hope I'm not being a bit thick.  Maybe I'm missing something.

All the best.  MikeC 2CQR Ltd.

**Comment by franciscave** [comment]
I think you're onto something, Mike. At present there is no explicit mechanism for differentiating between two Contact entities of the same type (e.g. phone numbers) for a specific Patron. My suggestion for addressing this would be to add new codes to the code list CMT (communication type) for 'primary phone number', 'primary email address', 'primary postal address'. There are other ways of addressing this, but they would mostly be more disruptive of the existing XML schema.

**Comment by franciscave** [comment]
This was discussed at the Technical Panel meeting on 28 June. It was agreed to add new codes to code list CMT for code values 'Primary phone number', 'Primary email address' and 'Primary postal address'. It should be documented that a Patron may only link to a single Contact for each of these communication types.

**Comment by franciscave** [comment]
I have added code values for 'Primary phone number' ('11'), 'Primary email address' ('15') and 'Primary postal address' ('16') to code list CMT, with notes that a Patron may only reference one Contact entity for each of these communication types.
