### ISSUE TITLE
Why is location-ref repeatable under associated-location

### ISSUE THREAD

**Issue by mdovey** [anthonywhitford/bic-lcf#35]
I can understand why associated-location is repeatable under patron, item etc. e.g. in the following xml

````xml
     <patron>
.    ..
       <associated-location>
         <association-type>03</association-type>
         <location-ref>http://someserver/lcf/1.0/location/someid</location-ref>
       </associated-location>
       <associated-location>
         <association-type>03</association-type>
         <location-ref>http://someserver/lcf/1.0/location/someotherid</location-ref>
       </associated-location>
     </patron>
````

However, in the schema location-ref is repeatable within a single associated-location element permitting the following:
 
````xml
     <patron>
.    ..
       <associated-location>
         <association-type>03</association-type>
         <location-ref>http://someserver/lcf/1.0/location/someid</location-ref>
         <location-ref>http://someserver/lcf/1.0/location/yetanotherid</location-ref>
       </associated-location>
       <associated-location>
         <association-type>03</association-type>
         <location-ref>http://someserver/lcf/1.0/location/someotherid</location-ref>
         <location-ref>http://someserver/lcf/1.0/location/yetanothersomeotherid</location-ref>
       </associated-location>
     </patron>
````
Is this intentional or just an error in the schema?

**Comment by franciscave** [comment]
I think this is an error in the schema, but the schema is consistent with the documentation, so in that case the error originated in the documentation. I cannot think of a good reason why the element location-ref should be repeatable within associated-location.

**Comment by anthonywhitford** [comment]
Agreed.

**Comment by mdovey** [comment]
Changed in schema

**Comment by franciscave** [comment]
I have changed the cardinality of location-ref from '1-n' to '1' in the definitions of both entities E02 Item and E03 Patron in the main spec and in the XML binding spec.
