### ISSUE TITLE
Clarification of E01D18 - Number of copies in stock

### ISSUE THREAD

**Issue by mdovey** [anthonywhitford/bic-lcf#37]
Can I clarify what is meant by

E01D18 	Number of copies in stock

Is it the number of items the library currently owns - i.e. would exclude items with the status of lost, missing, on order.

Or is it the number of items currently available for loan - i.e. would exclude items already on loan or reserved.

Or is it the number of items immediately available for loan - i.e. would exclude those on waiting to be reshelved or in transit between locations

What about items temporarily withdrawn from circulation e.g. for repair? Or permanently withdrawn from circulation but still owned (e.g. reference only items)?

**Comment by franciscave** [comment]
LCF describes E01D18 as "Number of copies in stock / holding". The term "copy" and "item" are synonymous in LCF. An item (E02) is described as "An identified copy of a manifestation that is in a library's stock / holding". An item has a mandatory element E02D11 Circulation status, which uses list CIS. Among the various status codes are ones that mean "Lost", "Missing" and (curiously) "On order", as well as "Withdrawn from circulation for repair". Whether this matches current practice I am not qualified to say, but this is based upon SIP2, so I presume it has some currency, and the implication is that any item, regardless of its status, is part of the stock or holding of the library.

**Comment by franciscave** [comment]
Putting it another way, if there is an entity representing a copy or item, that item is by definition part of the stock/holding of the library.

**Comment by mdovey** [comment]
I'm not sure that helps.

I'm currently writing some (server-side) code to automatically populate some of the read-only numeric fields.

The simplest way of populating E01D18 is to use the total number of item entities attached to the manifestation entity. This is simply the number of item-refs in the manifestation record. If this is correct, then I'd question the usefulness of this field, since the client can very easily count the number of item-refs in the returned record too.

On the other hand, a more sophisticated way might be to iterate through the attached item entities and only count those with certain circulation statuses (e.g. discount those which are lost or missing). The question is which status should be counted and which shouldn't.

My current code looks like this, but is this correct?

''''
int stock = 0;
for (Item i: items) {
	switch (i.getCirculationStatus()) {			
		case VALUE_1: //Other unknown
			break;
		case VALUE_2: // On order
			break;
		case VALUE_3: // Available
			stock++;
			break;
		case VALUE_4: // On loan
			stock++;
			break;
		case VALUE_5: // On loan - not to be recalled until earliest recal date
			stock++;
			break;
		case VALUE_6: // In process
			stock++;
			break;
		case VALUE_7: // Recalled
			stock++;
			break;
		case VALUE_8: // On hold shelf
			stock++;
			break;
		case VALUE_9: // To be reshelved
			stock++;
			break;
		case VALUE_10: // In transit
			stock++;
			break;
		case VALUE_11: // Claimed returned
			stock++;
			break;
		case VALUE_12: // Lost
			break;
		case VALUE_13: // Missing
			break;
		case VALUE_14: // All copies withdrawn 
			break
		case VALUE_15: // Withdrawn from circulation for repair
			break
		case VALUE_16: // Withdrawn from circuation
			break
		default:
			break;
	}
}

**Comment by franciscave** [comment]
I think that there are a number of entity elements that are in a similar category, i.e. their values could be computed by performing a suitable query on the database. Another example would be E03D08 Number of items on loan, which could be computed by retrieving the list of all current loans that reference the patron in question. 

I'm afraid I cannot recall the logic for including these "number of" elements, but I presume that it had something to do with not wanting the user terminal to have to do too much data retrieval to provide some commonly-requested statistics. Maybe someone else can remind me...

**Comment by mdovey** [comment]
Sorry, I think you've missed my point. The problem is that I don't understand the semantics of what "in stock" means.

Does it mean 

- the item is owned by the library; or
- the library owns a copy which is loanable (i.e. not a reference only copy, or recently ordered and still in the post, or withdrawn for repair...); or
- the library owns a copy which is immediately available for load (i.e. not out on loan or on the returns shelf etc..)

or is it determined by the library itself?

**Comment by anthonywhitford** [comment]
Since this question is really about how you are implementing your pseudo-lms in order to provide an LCF web services endpoint, I'm not sure this is the right place for this conversation, but mainly because an actual LMS already has a value for this name and hence its not a complex question. 

Having said that, "In Stock" most closely aligns with your second bullet point definition. For clarification reference items are "In Stock" but are typically not loanable. Library specific rules decide what is loanable and what is not. "In Stock" does not denote availability.

**Comment by mdovey** [comment]
My concern was that whilst an LMS might have a value with this name, will different LMS systems have the same concept of "in stock".

If there's a common understanding\practice we should reference that in the spec just to be precise. If different LMS systems or even different implementations have different concepts\practice of "in stock", I have concerns about clients being able to use this field in an interoperable way.

**Comment by franciscave** [comment]
This was discussed at the Technical Panel meeting on 28 June. It was agreed that each LMS has its own definition of what is meant by "in stock", and LCF should specify that this term is implementation-defined. There is no common understanding/practice for use of the term, so its use will not be entirely interoperable.

**Comment by anthonywhitford** [comment]
As there is nothing remaining to be done on this issue, closing.
