### ISSUE TITLE
Additional SIP2 64 Patron Response Fields

### ISSUE THREAD

**Issue by SimonInsight** [anthonywhitford/bic-lcf#41]
Under SIP2, many implementations extended message 64 (Patron Information response) to return additional fields that were not defined in the original specification. Although the field identifier differed between implementations, most LMS providers added, as a minimum, fields for Borrower Category and Internet Flag (a field denoting whether the borrower had signed a parental consent form to permit access to the Internet).

Looking specifically at entity E03 Patron in the current version of the documentation, I see that these fields have not been included.

Presuming that most customers will expect the same level of functionality as they currently receive under SIP2, is there any intention to include those additional fields that were added to SIP2 message 64 or have these been omitted intentionally?

**Comment by mdovey** [comment]
I've done a quick comparison between SIP2 and the SIP3 drafts for Patron Information Response. In summary

    personal name was broken into:
      patron name prefix
      patron first name
      patron middle name
      patron last name
      patron name suffix

    home address broken into:
      patron address - street
      patron address - city
      patron address - state
      patron address -postal code
      patron address - country

    Additional fields:
      secondary patron identifier
      patron expiration date
      deposit balance
      patron text msg address
      patron birth date
      PAC access type
      patron type ["such as child, adult, juvenile"]
      library specific user type 1
      library specific user type 2
      library specific user type 3
      library specific user type 4
      library specific user type 5
      library specific user type 6
      library specific user type 7
      library specific user type 8
      library specific user type 9

**Comment by franciscave** [comment]
I suggest that we discuss additions to the Patron and Content entities at the next Technical Panel meeting. For example, we could introduce the following:

E03C23 Structured name
E03D23.1 Name part type (new code list required, based on SIP3, possibly with additions)
E03D23.2 Name part (string)

E09C08 Structured communication locator
E09D08.1 Communication locator part type (new code list required, based in SiP3, possibly with additions)
E09D08.2 Communication locator part (string)

**Comment by franciscave** [comment]
This was discussed at the Technical Panel meeting on 28 June. It was agreed that specific use cases need to be defined, based upon the requirements of actual or planned LCF implementations, before adding borrower category, internet flag, structured name or address elements, or any other new elements, to LCF.

**Comment by franciscave** [comment]
As a consequence of discussion at the Technical Panel meeting on 22/09/2016 I will add documentation for Patron Category (0-1) and Patron Tag (0-n), both as string types. I will also add Patron expiration date and Deposit balance. This issue can be closed once the schema changes are made.

We agreed to re-open vCard issue (#17).

**Comment by franciscave** [comment]
I have revised the document to add the new properties to the Patron entity in the LCF v1.0.1 Specification and in the XML binding specification. Note that Deposit balance is a composite contain a mandatory currency amount and an optional currency code.

**Comment by mdovey** [comment]
I'm going to close this on the basis that if there are other LMS extensions to SIP2 which aren't handled by these new patron fields, then a use case\scenario should be submitted as a new issue.
