### ISSUE TITLE
Alerting a patron to a new note

### ISSUE THREAD

**Issue by colinparkeruk** [anthonywhitford/bic-lcf#50]
I suggest the addition of an extra field, e.g. E03D21.4 - Acknowledged, to the Patron entity. This would enable a kiosk to alert users when a note has been added to their account that they haven't already marked as being read.

**Comment by franciscave** [comment]
What would the values of this field be, or would it be an empty element flag (like Q11D07), i.e. included only if the note had been read?

**Comment by franciscave** [comment]
See my response to issue #52 .

**Comment by mdovey** [comment]
Subsumed into issue #59
