### ISSUE TITLE
Alerting a patron to the fact that their account is about to expire

### ISSUE THREAD

**Issue by colinparkeruk** [anthonywhitford/bic-lcf#51]
I suggest the addition of a new field, ExpiryDate, to the Patron entity. Related to this, an addition to the PNS code list of 'Expired' would be required.

**Comment by franciscave** [comment]
We currently have E03D30 Patron expiration date. Adding "Expired" to code list PNS sounds like a good idea, but do we need the new field?

**Comment by colinparkeruk** [comment]
Apologies, missed E03D30, so no new field required.

**Comment by franciscave** [comment]
I've added code value '16' = 'Account expired' to code list PNS.

**Comment by mdovey** [comment]
Schema update
