### ISSUE TITLE
New note type for promotional messages

### ISSUE THREAD

**Issue by colinparkeruk** [anthonywhitford/bic-lcf#52]
To distinguish a note in a Patron entity as being for a promotion, I suggest the addition of a new 'Promotion' note type.

**Comment by franciscave** [comment]
The code list NOT is effectively empty at present. Perhaps now is a good point at which to review the use of the note composites with all entity types and decide what types of notes are needed for each entity type, insofar as we can determine it right now. On reflection, I think we're in danger of confusing two different concepts: a note about some entity (about an item, a manifestation, a location, a patron) and a communication to someone. Maybe we could definite several note types for Patron notes, all of which would be notes of messages sent to the Patron, e.g. 'Warning message sent to patron', 'Promotional message sent to patron'. My concern about promotional messages is that it might be necessary to add these to many or even all Patron records, which would involve a lot of duplication. I'm inclined to wonder whether there might be merit in defining a new Message (or Notification) entity for general messages that aren't specific to individual patrons. Obviously this will have to fit with the data model for such things in current library management systems.

**Comment by colinparkeruk** [comment]
I agree that this needs a wider discussion. WRT promotional messages, although this may target many patrons, it may still be a subset, e.g. only applicable to adults over 60.

**Comment by mdovey** [comment]
Subsumed into issue #59
