### ISSUE TITLE
Inform a patron of their position in a reservation queue

### ISSUE THREAD

**Issue by colinparkeruk** [anthonywhitford/bic-lcf#53]
I suggest the addition of a field to the Reservation entity to indicate the patron's current position in the queue for that Manifestation or Item.

**Comment by franciscave** [comment]
This could perhaps best be inserted following E06D11 Reservation status, which will indicate that the patron is in the hold queue. I presume that the value would be an integer, '1' indicating that they are at the top of the queue?

**Comment by franciscave** [comment]
I've added new element E06D15 to both the LCF v1.0.1 documentation and the XML binding.
