### ISSUE TITLE
Add support for family/group patron accounts

### ISSUE THREAD

**Issue by colinparkeruk** [anthonywhitford/bic-lcf#54]
To allow a 'lead' patron to view their family's/group's loans, etc. and borrow, renew , etc. for them, I suggest adding a repeatable 'associated patron' field to the Patron entity.

**Comment by franciscave** [comment]
I propose:
-----------|---------------------------|----------
 E03C32     |  Associated patron          |  0-n       
 E03D32.1  | Patron association type   |   1         
 E03D32.2  | Patron reference             |    1        
-----------|---------------------------|----------

**Comment by franciscave** [comment]
So much for Markdown working in issue comments...

**Comment by franciscave** [comment]
A new code list PAT will be needed for Patron association type. What would be the code values? I suggest:
"is member of group led by", "is leader of group also containing". The LMS would need to ensure that the groupings make sense, e.g. a group can only have one leader. This makes me wonder whether it would be more robust to define Patron Group entity, which would then have a single leader and multiple other members. We would then have E03C32 Associated patron group (0-n). That way a Patron could be a leader or member of several groups (family, club, school class,...).

**Comment by colinparkeruk** [comment]
There may be more than one leader in a group, e.g. mother and father.

**Comment by franciscave** [comment]
Good point. However, can someone be in more than one group? If so, I think we're going to need a Group entity, so that it is clear which group a member is a member or leader of. Even if we don't have a separate entity for groups, we'd still need a group ID.

**Comment by franciscave** [comment]
Following discussion at the Technical Panel meeting today, I now propose:
```
-----------|-------------------------------|----------
E03C32     | Associated patron             | 0-n
E03D32.1   | Patron association type       | 1
E03D32.2   | Patron reference              | 1
E03C33     | Associated patron group       | 0-n
E03D33.1   | Patron group association type | 1
E03D33.2   | Patron reference              | 1-n
-----------|-------------------------------|----------
```
On the understanding that association types, both for individuals and for groups, would be LMS-dependent, I suggest that the association type value would be of type string and not controlled by a code list. We could always add a controlled code list in a future revision of LCF.

**Comment by franciscave** [comment]
I think we can dispense with the structure E03C32 for an individual patron, as this is simply a special case of a patron group, so my proposal now is simply:
```
-----------|-------------------------------|----------
E03C32     | Associated patron group       | 0-n
E03D32.1   | Patron group association type | 1
E03D32.2   | Patron reference              | 1-n
-----------|-------------------------------|----------
```
The assumption/recommendation would be that E03D32.1 Patron group association type should encode all the information that would be needed to identify the type of patron group and the patron's role within it, so the following would have distinct code values: "lead patron in family group", "lead patron in school group". The group would, in effect, be defined by the lead patrons of that group.

I can imagine some use cases that might be difficult to handle. For example, suppose that two teachers are lead patrons for a school group. Would they both be able to view each other's borrowing records? Or would they each define the same group of students whose records they have access to, but excluding each other's? If one teacher updates their details to add an extra student to a group, how would the LMS know to add the extra student to the other teacher's details? 

I think that, if for now we avoid adding a new entity for Patron Groups, we will need a mechanism for keeping patron group information in sync across multiple patron records, which we could do in one of two ways: either (a) we identify all groups that have multiple leader patrons; or (b) we make explicit who the other leader patrons are. These could both be accommodated by the following structure:
```
-----------|-------------------------------|----------
E03C32     | Associated patron group       | 0-n
E03D32.1   | Patron group association type | 1
E03D32.2   | Patron group identifier       | 0-1
E03D32.3   | Lead patron reference         | 0-n
E03D32.4   | Patron reference              | 1-n
-----------|-------------------------------|----------
```
The purpose E03D32.2 and E03D32.3 would be to enable the LMS to keep group information in sync across multiple patron records, and would not automatically give a lead patron the right to see details of other lead patrons of the same group.

**Comment by franciscave** [comment]
The following has been added to LCF v1.0.1:
```
E03C33     | Associated patron group    |           | 0-n      |            | A group of patrons with which this patron is associated either as a leader or a member. <br/>*Added v1.0.1* 
E03D33.1   | Patron group association type |        | 1        | Code       | LCF code list **[[PGP\|LCF-Code-Lists#PGP]]**
E03D33.2   | Patron group identifier    |           | 0-1      | String     | A unique identifier of the group
E03D33.3   | Lead patron reference      |           | 0-n      | String     | Leader(s) of the group 
E03D33.4   | Patron reference           |           | 0-n      | String     | Other member(s) of the group 
```
Note that the cardinality of E03D33.4 differs from what I proposed previously, because there may be no other patrons in the group other than the patron in question (e.g. a child) and a lead patron (e.g. a parent or teacher). It will be up to the LMS to determine whether patrons who are members of a group are entitled to know who other members of the group are, but I think a patron associated with a particular group would normally be entitled to know who the lead patrons of that group are.

I've made corresponding additions to the XML binding for entity E03, and I've added the new code list PGP.

**Comment by anthonywhitford** [comment]
Discussion in the Technical Panel meeting on 2018-05-02 agreed that the authentication and authorisation work was now correctly specified and this issue can be closed.

**Comment by franciscave** [comment]
This was reviewed by the Technical Panel earlier today. The proposed code list PGP will be modified to contain just two codes: 01 Patron member of group and 02 Lead patron member of group. We agreed that "lead patron" means a patron permitted to perform any action on behalf of any member of the group.

The concept of a group type may be relevant in some implementations and not in others. A new element will be added 'Patron group type', with cardinality 0-1, with an uncontrolled string value. Creation of a controlled list of code values may be worth considering at a later date, but it is not possible to come up with a definitive list of group types at this stage.

We considered whether LCF needs to record whether a Patron has consented to be a member of a specific group. After discussion it was agreed that this does not need to be recorded in LCF, as it will be part of a library's terms and conditions of service to state what kinds of patron groups can be established and how consent is given when a group is established or a new member joins a group.

**Comment by franciscave** [comment]
Added E03D33.5 Patron group type to LCF Version 1.0.1 specification. Consequently added 'group-type' to LCF v1.0.1 XML Binding for entity E03.

Modified code list PGP to contain just two code values for 'Patron member of group' and 'Lead patron of group'.

**Comment by franciscave** [comment]
At today's Subgroup meeting it was agreed to implement this as specified.
