### ISSUE TITLE
How do I set a PIN for a borrower

### ISSUE THREAD

**Issue by anthonywhitford** [anthonywhitford/bic-lcf#56]
Only required where the BARCODE/PIN authentication is required, and there is a need to reset / change a Patron's PIN.

POST /lcf/1.0/patron/{unique-id}/pin
456576

PIN value passed over an encrypted channel in plain text, such that the enforcing system has the original value in order to apply the system's hashing.

**Comment by franciscave** [comment]
I've added a new function '18' to the LCF Rest Web Services specification. Please check. I'm not sure whether the Patron PIN is always stored as a property of the Patron record.
