### ISSUE TITLE
Patron entity addition - Parental Consent / Internet Flag

### ISSUE THREAD

**Issue by Neil-IMIL** [anthonywhitford/bic-lcf#58]
Request for additional information about the borrowers in the patron entity.  The request is to include existing functionality implemented by most of the UK main LMS's where additional information from the borrower record is returned via extensions to the current SIP2 response 64 and in newer subsequent web services implementations.  This functionality relates to Parental Consent / internet access, although referred to in different ways by different systems and authorities, and provides in the main implementation a yes, no or null response / value for each borrower.  This information is used along with other borrower specific information to authorise a user after authentication to determine if the requested functionality is available to the current user

**Comment by franciscave** [comment]
Matthew, are you able to advise how this is handled in the NISO SIP3 proposals? It would be good to adopt a compatible approach. Anthony, do you have views on this? Is it sufficient to have a code list with two values: 'Yes' and 'No'? The value 'unspecified/unknown' could be represented simply by the field/element being omitted.

**Comment by mdovey** [comment]
SIP3 added patron type ["such as child, adult, juvenile"] but nothing more.

Might be special case of #55

**Comment by mdovey** [comment]
Closed as special case of #55
