### ISSUE TITLE
Entity documentation incorrect when compared with XSD schema

### ISSUE THREAD

**Issue by neilstevens2005** [anthonywhitford/bic-lcf#6]
In the XSD schema the Patron entity has a 1-1 relationship with a Contact-ref (i.e. a cardinality of 1).  Yet in the entity documentation the cardinality is specified as "0-1".  

Similarly in the XSD schema a Contact entity has a 1-1 relationship with a Patron-ref (i.e. a cardinality of 1).  Yet in the entity documentation the cardinality is specified as "1-n".

Could the entity documentation be updated to reflect the current schema?

**Comment by franciscave** [comment]
Needs discussion. I'm not sure that the schema is correct. The introduction of the Contact entity has proved to be problematic in any case. I think we need to decide whether the Contact entity is needed at all before deciding what its relationship should be with the Patron entity.

**Comment by anthonywhitford** [comment]
Given that we will be collapsing the Contact and Patron entities down into a single Patron entity, when that happens this issue will be resolved.
