### ISSUE TITLE
How to return an empty list of entities

### ISSUE THREAD

**Issue by mdovey** [anthonywhitford/bic-lcf#64]
When requesting a list of entities (e.g. http://server/lcf/1.0/loans) what should the response be if there are no entities of that type?

Two possibilities would be to 

1) return an lcf-entity-list-response with no entity elements, e.g.

```xml
<lcf-entity-list-response>
    <entity-type>loans</entity-type>
    <ns2:totalResults>0</ns2:totalResults>
    <ns2:itemsPerPage>0</ns2:itemsPerPage>
    <ns2:startIndex>0</ns2:startIndex>
</lcf-entity-list-response>`
```

2) return a HTTP error response (e.g. 404).

The latter option whilst technically correct (no entities were found) could be confused with the url being invalid (e.g. the LCF server not supporting retrieval of entities of that type, rather than it does support retrieval of that type of element but none currently exist).

The former "feels" more correct. However, at present the LCF documentation and XML schema is of cardinality 1-n, so the response in (1) is currently invalid.

My recommendation would be to change the cardinality of entity to 0-n. Any comments or alternative views?

**Comment by franciscave** [comment]
The current documentation suggests that there is an alternative: HTTP 207 and an exception condition of type '08'. Somewhat unhelpfully, the documentation of exception code '08' suggests that it is "equivalent to HTTP 404", which I don't think is actually correct, since an empty list is still a resource. If we allow an empty list to be returned without an exception condition, we will need to review the use and validity of exception condition code '08' - see (LCF-Code-Lists#EXC).

**Comment by mdovey** [comment]
There was an e-mail discussion whether HTTP 207 made sense or was desirable but I don't think we came to a conclusion - I've raised this as issue #65

**Comment by mdovey** [comment]
Coming back to this specific question, and a request to (for example)

http://server/lcf/1.0/class-schemes

HTTP Response 404 with an XML Payload for EXC05 could mean that class schemes are not supported by the sever

whereas HTTP Reponse 404 with XML Payload EXC08 could mean that class schemes are supported by the server but there are any schemes currently on the system

**Comment by franciscave** [comment]
These are reasonable interpretations, although in practice I'd have thought that EXC08 would be unlikely to be returned in the case of a simple request for all 'class-schemes'. It is more likely to be returned when searching for entities with a specific search criteria.

**Comment by mdovey** [comment]
a request for all class-scheme is effectively a search for entities with an implicit search\selection criteria of all (of that specific type).

In general a search for entities (with or without explicit search criteria) can return one of the following:

- no list (in the case of an error, including that the particular entity type is not supported by the service)
- an empty list (because there are no results)
- a populated list (the normal case)

There is a case to be able to distinguish between no list, and an empty list. 

I don't think there is a particularly strong case* to be able to distinguish between an empty list returned when there is no explicit search criteria versus an empty list returned when there is an explicit search criteria. So we should either return an EXC08 in both cases, or in neither case (instead returning an empty entity list XML and in effect deprecate EXC08).


[* there is a very weak case of distinguishing between an empty list because the search criteria is too specific, but you might get results if you weakened the criteria (represented by EXC08), versus an empty list because there are no entities of that type on the system yet, so changing the criteria won't help (represented by an empty entity list XML), but this seems an excessive and unnecessary nuance).]

**Comment by mdovey** [comment]
I think my preference would be to deprecate EXC08. I suspect many clients will include code which would be variants of the following XSLT:

```xsl
<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:lcf="http://ns.bic.org.uk/lcf/1.0" xmlns:os="http://a9.com/-/spec/opensearch/1.1/">
  <xsl:template match="/lcf:lcf-entity-list-response">
    <html>
      <body>
        <h2>Results</h2>
        Showing <xsl:value-of select="os:itemsPerPage" /> results of <xsl:value-of select="os:totalResults" />
        <ol start="{os:startIndex + 1}">
          <xsl:for-each select="lcf:entity">
            <li><a href="{@href}"><xsl:value-of select="@href"/></a></li>
          </xsl:for-each>
        </ol>
      </body>
    </html>
  </xsl:template>
</xsl:stylesheet>
```
which can cope happily with both populated and unpopulated entity list xml responses, and reserve handling non 200 responses for errors (as opposed to searches which have run successfully even if they've not found anything).

**Comment by franciscave** [comment]
I'm convinced by this. Let's mark EXC08 as deprecated. If the expected response is a list of entities and not a specific entity, an empty list is a valid response.
