### ISSUE TITLE
Handling loans from a library in a consortium without using inter-library loan

### ISSUE THREAD

**Issue by franciscave** [anthonywhitford/bic-lcf#67]
The following query has been received from Steve Wright at Bucks County Council libraries:

Hi Francis

I’ve had a query about handling loan information using LCF standards. 

Bucks are a member of the SELMS consortium (currently 11 authorities) and we all use the same LMS: Civica’s Spydus. We are able to place reservations on each-others stock. When these items arrive we are able to issue them directly onto our local system without need for any inter-library loan process, extra cataloguing or assigning temporary barcodes.

This means we are often in a situation where a customer has items on-loan from us and from other authorities. To maintain an element of separation, so it is clear which books are ours and which belong to other authorities, the customer has two lists of loans. Current loans and Loans other. Loans other lists any items borrowed from other authorities.

All of this information is visible to our customers when they are logged in to our OPAC.  

Currently our RFID Kiosks connect to our LMS using SIP2 protocol. When our customers log in on the kiosks they are unable to see their Loans other. I suspect this is because the loan needs to express not only the loan detail but also the authority the item is from.  I do not know if SIP2 is able to handle this extra message data. 

My question is, how would LCF handle this information?  

I can see the Item Entity contains two elements that might handle it 

E02C05 – Item owner
E02C06 – Associated location.

I cannot see any location data elements present in the Loan Entity.

What are your thoughts on this?

Thank you.

Steve

**Comment by franciscave** [comment]
This is how I replied to Steve:

Hi Steve

I think the LCF technical panel should discuss this. It could be argued that knowing which library owns the item (E02D05) is sufficient, but there may be advantages in the Loan entity being able to identify the lending library, which would usually be the library owning the item, but maybe there would be occasions when that isn’t the case… e.g. one library lends stock to another library for an extended period during which time the receiving library lends items from that stock as if they were their own stock?

**Comment by franciscave** [comment]
We discussed this at today's Technical Panel meeting. It was agreed that I would respond to Steve that LCF allows a Patron's "home" library to be defined (associated location of type '03' - see E03C03 and list LAT), and also allows the owner of an Item loaned to that Patron to be defined (see E02D05). We think that, between them, these two pieces of information put the Loan into the "other" category that Steve mentions, so no additional information needs to be stored with the Loan.

**Comment by colinparkeruk** [comment]
Do we need a distinction between Library and Authority here? The patron's home library may differ from the library that owns the item if the 'library' refers to a branch but those branches may be in the same authority, in which case they shouldn't appear in the 'other' list.

**Comment by franciscave** [comment]
Thinking about this further, an Authority is a legal entity and is distinct from an Institution defined by its Location. I think it could be argued that LCF currently conflates - and thereby confuses - the concepts of a institution as a legal entity and an institution as a geographical location, in a possibly mistaken attempt to simplify the entity model and on the grounds that a location can frequently be used to represent an institution such as a library. The emergence of consortia puts a strain on this over-simplification. I think we need to consider adding a new Authority entity, which could be associated with multiple Locations (physical and virtual), and which could also be associated with Authorisations as well as with Patrons (e.g. "home authority") and Items (e.g. "owner").

**Comment by mdovey** [comment]
Special case to be addressed by issue #68
