### ISSUE TITLE
Out of hours / unmanned site access 

### ISSUE THREAD

**Issue by Neil-IMIL** [anthonywhitford/bic-lcf#69]
It appears that LMS’s are working with Access Control Systems to provide an additional level of borrower authorisation to manage out of hours / unmanned site access using additional SIP2 extensions and alternative means.  Where should this be included in LCF?

**Comment by colinparkeruk** [comment]
To add some detail, I asked my Danish colleagues for information on the existing SIP2 implementation for open+.

The open+ configuration includes  an 'Open Library Field Name' setting where the extension field in the PatronInformationResponse can be specified, examples used are 'PH' and 'U4'. Example values used are 'AD_PC_OPEN', 'NON_OPEN', 'STAFF', 'CUSTOMER'.

The AF (ScreenMessage) field is utilised to provide user feedback, e.g. when entry is prohibited.

It is possible to get patron information before providing a PIN. As well as being able to provide messages to the user immediately after scanning their card it is also useful in the situation where an external card reader has no PIN pad. Once in the lobby, the user scans their card again and then enters their PIN.

**Comment by mdovey** [comment]
Should be addressed by new feature described in issue #55
