### ISSUE TITLE
Why do we define our own Date and DateTime types and not use the standard ones?

### ISSUE THREAD

**Issue by neilstevens2005** [anthonywhitford/bic-lcf#7]
Date and DateTimes.

In the XSD schema we define our own date and datetime formats as:

	<xs:simpleType name="dateFixedFormat">
        <xs:restriction base="xs:string">
            <xs:pattern value="2\d\d\d(0[1-9]|1[0-2])(0[1-9]|1[0-9]|2[0-8])"/>
            <xs:pattern value="200[048]0229"/>
            <xs:pattern value="2[1-9]0[48]0229"/>
            <xs:pattern value="2\d([2468][048]|[13579][26])0229"/>
            <xs:pattern value="2\d\d\d(0[13-9]|1[0-2])(29|30)"/>
            <xs:pattern value="2\d\d\d(0[13578]|1[02])31"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="dateTimeFixedFormat">
        <xs:restriction base="xs:string">
            <xs:pattern
                value="2\d\d\d(0[1-9]|1[0-2])(0[1-9]|1[0-9]|2[0-8])T([01][0-9]|2[0-3])[0-5][0-9][0-5][0-9](Z|[+\-](0[0-9]|1[0-2])(00|15|30|45))?"/>
            <xs:pattern
                value="200[048]0229T([01][0-9]|2[0-3])[0-5][0-9][0-5][0-9](Z|[+\-](0[0-9]|1[0-2])(00|15|30|45))?"/>
            <xs:pattern
                value="2[1-9]0[48]0229T([01][0-9]|2[0-3])[0-5][0-9][0-5][0-9](Z|[+\-](0[0-9]|1[0-2])(00|15|30|45))?"/>
            <xs:pattern
                value="2\d([2468][048]|[13579][26])0229T([01][0-9]|2[0-3])[0-5][0-9][0-5][0-9](Z|[+\-](0[0-9]|1[0-2])(00|15|30|45))?"/>
            <xs:pattern
                value="2\d\d\d(0[13-9]|1[0-2])(29|30)T([01][0-9]|2[0-3])[0-5][0-9][0-5][0-9](Z|[+\-](0[0-9]|1[0-2])(00|15|30|45))?"/>
            <xs:pattern
                value="2\d\d\d(0[13578]|1[02])31T([01][0-9]|2[0-3])[0-5][0-9][0-5][0-9](Z|[+\-](0[0-9]|1[0-2])(00|15|30|45))?"
            />
        </xs:restriction>
    </xs:simpleType>
	
I think it would make far more sense to use the standard XSD Date and DateTime types (defined here http://www.w3schools.com/schema/schema_dtypes_date.asp).  The advantage of this is many software libraries written in different programming languages will parse and build standard XSD date and datetime values.  This would mean implementors would not need write custom parsing and building code for these fields.  Defining our own DateTime type also makes the interface confusing (since when implementors see "DateTime" type in the entity document they will assume this means the standard XSD DateTime type).

**Comment by neilstevens2005** [comment]
Also the Date and DateTime types defined only allow years beginning with "2".  It's possible that some historic data from before 2000 may be surfaced, for example the dateTime on a Note.  Therefore it does not make sense to limit dates to years beginning with a "2"

**Comment by franciscave** [comment]
Agreed. We should correct the schema.

**Comment by franciscave** [comment]
...and the simple way to do this is to use xsd:date and xsd:dateTime.

**Comment by anthonywhitford** [comment]
Any field which was dateFixedFormat has been updated to be xs:date.
Any field which was dateTimeFixedFormat has been updated to be xs:dateTime.
Any field which was dateOrDateTime has been updated to be xs:dateTime.

**Comment by anthonywhitford** [comment]
@franciscave - Can you review the committed amendment please?

**Comment by franciscave** [comment]
I have done so and have incorporated corresponding changes in documentation.
