### ISSUE TITLE
How should a manual charge be created?

### ISSUE THREAD

**Issue by anthonywhitford** [anthonywhitford/bic-lcf#75]
Within the Review Panel meeting on 22nd February 2018, the question was raised on how to create a manual charge. This is a charge against a Patron's account, for something which is not derived from a Library rule. For example, charging for printing or PC use.

The point was made that the existing documentation is unclear about how this should be done, and could we provide a definitive process. The documentation should therefore be updated.

**Comment by franciscave** [comment]
This is a requirement for the description of a function that is neither a circulation management function nor a stock management function, so I propose to create a new section in LCF v1.0.1 entitled 'Miscellaneous other functions', or just 'Other functions' if preferred. Within that section I propose to specify a new function 'Apply new Charge to Patron account', which will be specified as combining the following core functions:

- Unless this is a cancellation, create a charge record of the appropriate type (code list CHT), with a reference to the associated patron record. If cancelling the charge, search for and either delete or modify accordingly the charge record.
- Unless this is a cancellation, modify the patron record to include a reference to the new charge. If cancelling the charge and deleting the charge record, modify the patron record to remove the reference to the cancelled charge.
- Unless this is cancellation, if adding the charge to the patron account changes the patron status (e.g. status code PNS11 or PNS14 now applies), modify the patron status accordingly. If cancelling the charge, make any necessary change to patron status.

I suspect we may need to add further code values to list CHT for this use case.

I will then create a corresponding section in the LCF v1.0.1 REST Web Service specification. This would essentially be a POST to create a new charge record, e.g.

POST http://192.168.0.99:80/lcf/1.0/patrons/1234567890/charges

with a new charge record attached as an XML payload; or a DELETE to cancel the charge. 

Just a reminder that in the REST Web Services specification we always use DELETE to cancel, not PUT, although LCF v1.0.1 would in principle support this alternative.

**Comment by anthonywhitford** [comment]
I don't think the second and third bullet points are required. The first one states how to create a charge, amend a charge or cancel a charge. The other bullet points are about modifying the content within a list of charges for a patron, which would be implicitly done by the LMS automatically. Equally, if there were reasons to change the state of a Patron due to the new charge, that itself should be a rule within the LMS. e.g. If Patron owes over £5, then apply a block. It should not matter where the £5 originated, it's the LMS' responsibility to apply the business rule.

**Comment by franciscave** [comment]
Hmm... but in the case of existing functions we generally specify creations/modifications/deletions that are consequential upon carrying out the function. See, for example, 13 Patron payment, where we explicitly state that the corresponding charge records should be modified to update charge status. Should we be removing all such consequential changes?

**Comment by franciscave** [comment]
I think we may need a new charge status code for 'cancelled'. At present the only options are to delete the charge (that's how we would do it REST-fully) or change its status to CHS03 (fully paid). Any thoughts?

**Comment by franciscave** [comment]
A new function 31 has been added to the LCF v1.0.1 specification. Please review before I make a corresponding change to the REST Web Service specification.

**Comment by franciscave** [comment]
I have added function 31 to the REST Web Service specification.

**Comment by franciscave** [comment]
This was reviewed by the Technical Panel earlier today. Please review the documentation of function 31 in the LCF Version 1.0.1 specification and in the LCF 1.0.1 REST Web Service specification. Please also could I have views on the question that I raised in response to Anthony on 22 February: should we remove consequential record updates from descriptions of other functions, such as the second bullet point in 13 Patron payment in the LCF Version 1.0.1 specification? My gut feeling is that we should include consequential record updates, because I don't see how we can avoid doing so in the case of more complex functions such as 11 Check-out and I think we should be consistent. If consequential updates need to be included in the specification of function 31, I'll need to add these to the documentation.

**Comment by franciscave** [comment]
I've added the consequential changes to the description of function 31 in the LCF Version 1.0.1 specification. I shall now close this issue and open a new issue for discussion of whether and to what extent consequential record updates should be included in the description of LCF functions.
