### ISSUE TITLE
Miscellaneous schema bugs

### ISSUE THREAD

**Issue by mdovey** [anthonywhitford/bic-lcf#78]
Mispelling of Link in documentation for contact-ref element
Mispelling in name of simple type innstitutionIDType (sic)

**Comment by franciscave** [comment]
Can you point me to the mis-spelling in the documentation? I've corrected a duplication of the property reference E14D05.2 (now E14D05.3), if that is what you were referring to.

**Comment by mdovey** [comment]
The spelling error is in a xs:documentation element within lcf-v1.0-entities.xsd, not the supporting documentation.
