### ISSUE TITLE
ENT codes do not match entities

### ISSUE THREAD

**Issue by neilstevens2005** [anthonywhitford/bic-lcf#8]
The Entity document lists 12 Entities, while the Codes document lists11 ENT codes.  The first 9 ENT codes match the first 9 entities, however the last few seem out of sync.

The final 4 entities defined in the entity document are:
E09 - Contact
E10 - Title Classification Scheme
E11 - Title Classification Term
E12 - Selection Criterion

The final 3 ENT codes defined in the codes document are

ENT09 - Class scheme
ENT10 - Class code
ENT11 - Property

I suspect the codes document just needs updating to contain consistent information to the Entity document.

**Comment by franciscave** [comment]
Yes, the Contact entity is missing from the ENT code list. We need a discussion about the Contact entity before deciding how to fix this.

**Comment by franciscave** [comment]
We've agreed to dispose of the Contact entity, so I'll make the documentation changes.

**Comment by anthonywhitford** [comment]
We then reversed that decision, so the Contact entity remains, with some tweaks to the data that it holds.

**Comment by franciscave** [comment]
I've reinstated 'contacts' in the ENT code list.
