### ISSUE TITLE
Schema refactoring

### ISSUE THREAD

**Issue by mdovey** [anthonywhitford/bic-lcf#88]
I would suggest the following refactoring to the schema (which shouldn't impact the specification):

Extract the codelists into a separate xsd document
Extract generic types into a separate xsd document (currently there is only one - nonEmptyString)
Create a new type lcfEntityReference (based on nonEmptyString), and change the relevant xxx-ref elements to this type

The latter change should not change the Information Entity XML Binding but would make it easier for development tools to parse where a string is just a string and where a string is a reference to another Entity (for example in the REST implementation this could be used to validate that all references are URIs)

**Comment by franciscave** [comment]
Good idea.
