### ISSUE TITLE
Explain "selection criterion" (filtering???) on "Retrieve entity instance list" section in "LCF 1.0 REST Web Service Specification" document

### ISSUE THREAD

**Issue by neilstevens2005** [anthonywhitford/bic-lcf#9]
In section "Retrieve entity instance list" of the document "LCF 1.0 REST Web Service Specification" there is a table describing the "Format for request URI".  Row 8 in this table table appears to be a way to specify filter criteria and references “Q02D02.2” which as far as I can see does not exist.

None of the URI examples below the table use this parameter, and it is definitely not obvious how it should be used.  If we are to keep this URI parameter in the standard I think the following should be added:
-   An example GET list URI which uses filtering
-   A list of what is valid filtering criteria for each entity containing the exact strings which should be used as parameters in the URI.

The answer to the second question is not obvious (It is not possible to just use the name of each element in an entity which is what I expect the designers initially thought).  What if I wanted to filter Contacts on a specific phone number or email address.  A phone number is stored in element “locator” which is a child element of “communication-detail” (which is an element of contact entity).  “communication-detail” elements only contain phone numbers in their “locator” element if their “communication-type” element has a value of “01”, “02”, ”03”, or “04”.  An email address is similar except will have its “communication-type” element set to “05”. There is no obvious way to achieve filtering on these things.  (And no clearly defined way to use this parameter to filter on anything at all)

I think this parameter should be removed from the standard (since if it is included different implementations are almost sure to support filtering on different things leading to inconsistencies between implementations)

The standard already provides filtering on element-ref fields by supporting URI's in the format:

/lcf/1.0/manifestations/1234/items

The above example would return a list of items for manifestation ID 1234.  Being able to support URIs in this format means the standard already provides filtering for most common use-cases without the need for this "selection criterion" parameter in the URI.

**Comment by franciscave** [comment]
You're right that the use of filter criteria is not clearly explained. However, element Q02D02.2 does in fact exist and is documented under '02 Retrieve entity instance list' page page 29 of the LCF v1.0 documentation: it is the string value used with the chosen filter criterion. However, you make a serious suggestion that it will be impossible to make such selection criteria interoperable, as they will be highly dependent upon local conditions, and that we should remove this from the standard. I'm happy to discuss this proposal.

**Comment by franciscave** [comment]
We probably need to replace the existing Selection Criterion entity with a list of the selection criteria that can be used when retrieving entities of any given type, and in the web service implementation we should probably define a (small) minimum set that all implementations must support. However, this will need wider discussion with the Technical Panel in the first instance. In the meantime I'll draft appropriate documentation changes.

**Comment by franciscave** [comment]
We discussed this on the Technical Panel call. We're going to leave this issue open until after the Plugfest, when we hope to gather input as to what should be on the list.

**Comment by franciscave** [comment]
Further discussion re ENT12 and E12 can take place under issue #9.

**Comment by franciscave** [comment]
I suggest that we change the composite Q02C02 Selection criterion so that it must contain _either_ a reference to a selection criterion entity (Q02D02.1) _or_  a code value from a new selection criteria code list. This will allows us to retain the selection criterion entity in full LCF, but remove it from the web service implementation and instead just implement the new code list for now. I'll draft documentation for this.

**Comment by franciscave** [comment]
Initial suggestions for code list SEL, based upon a couple of stock management use cases.

**Use case: Stock Tidy**

Objective: To retrieve a list of items that are supposed to be available for loan at a specific location.
Entity: Item (E02)
Criteria: Location (location-ref="_identifier_"), circulation status "available" (circulation-status="03")
Criterion codes to be included in SEL: "location-ref", "circulation-status"

**Use case: Stock Search**

Objective: To retrieve a list if items that are recorded as out on loan and overdue, in order to check whether they have in fact been returned.
Entity: Item (E02)
Criteria: Circulation status "on loan" or "claimed returned" or "missing" (circulation-status="04" _or_ circulation-status="05" _or_ circulation-status="11" _or_ circulation-status="13"), Loan status "overdue" or "claimed returned by patron" (loan-ref=ANY _and_ (loan-status="02" _or_ loan-status="06"))
Criterion codes to be included in SEL: "circulation-status", "loan-status"
NOTE - Loan status is a property of Loan entities, not a property of Items, so searching for a list of items with loan status "overdue" implies searching for a list of items where the current active loan has a status "overdue".

**Comment by mdovey** [comment]
Re 'location-ref="identifier"' as per the discussion on schema names, I'd prefer it if -ref were used only when the value is a full URL reference.

I think in this case, the value would be just the identifier not a full URL, so perhaps location-id would be better?

However, how does this square with the normative documentation?

**Comment by franciscave** [comment]
Each of the Items that we are selecting contains a 'location-ref' element, whose content is a URI (in the web service implementation). Would we not specify the URI for the location in the search criterion? If not, what value would we use and how would the LMS know which Items to select based upon a value that is different from the one stored with the Item?

**Comment by mdovey** [comment]
Lets say we have a location entity

     <location>
       <identifier>mylocation</identifier>
       ...
     </location>

which is accessible via REST at http://myserver.com/lcf/1.0/locations/mylocation

then the selection criteria could be either

location-ref=http://myserver.com/lcf/1.0/locations/mylocation

or

location-ref=mylocation

The former requires URL escaping, whilst the latter is slightly more natural for http query parameters.

The former might be more versatile in that it would permit one LCF server using locations defined on another LCF server.

**Comment by franciscave** [comment]
On reflection I agree with your analysis. I can see that the extra versatility of using full URIs is a theoretical possibility, but I don't imagine there'll be much call for it. Let's use the '-id' suffix when the selection criterion is an association with an identified entity.

**Comment by franciscave** [comment]
Some more stock management use cases:

**Use case: Stock Search (Reservations)**

Objective: To retrieve a list of items that have been reserved and that are currently within the library.
Entity: Item (E02)
Criteria: Circulation status "available" (circulation-status="available"); Either this item has an associated reservation, or the manifestation of which this item is a copy has an associated reservation (has-reservation="true"). Might be narrowed down by location (location-id="xxx").

**Use case: Stock Search (Grubby Stock)**

Objective: To retrieve a list of items that match a set of criteria that suggest that they may be "grubby".
Entity: Item (E02)
Criteria: 
(a) Items that are borrowed a lot, i.e. the total number of loans of this item within a given period exceeds some figure (loan-period-start="_date_", loans-in-period-min="_n_")
(b) Items that are not or rarely being borrowed, i.e. the total number of loans of this item within a given period does not exceed some figure, which may be zero (loan-period-start="_date_", loans-in-period-max="_n_")
(c) Items that have been in stock a long time (acquisition-date-latest="_date_")
NOTE - There's no LCF Item or Manifestation property for the date on which it was acquired, so I'm not sure how this information would appear in the search results.

**Comment by franciscave** [comment]
The "Grubby Stock" use case is the least well supported in my opinion. It raises an important question of principle. Should it be possible to search for LCF entities based upon criteria for which there are no corresponding properties defined in LCF? The LMS may record loads of additional properties of an entity for which LCF currently has no representation.

**Comment by franciscave** [comment]
For the Stock Search (Reservations) use case, the criterion 'has-reservation="true"' could also be expressed as 'reservation-id=ANY', which might be preferable.

**Comment by franciscave** [comment]
The stock management use cases were reviewed by the Technical Panel at their phone meeting on 28 June. The following were agreed:

The use case "Stock Tidy" should be renamed "Stock Search (Available)", as libraries use the term "stock tidy" or "shelf tidy" to refer to the task of ensuring that shelved stock is in the correct location (i.e. in the correct position on a shelf).

The use case "Stock Search (Overdue)" can be simplified by searching for loans for which the end-due-date is earlier than a specified date, then request the items to which these loans refer. It was agreed that searching by circulation status or by loan status is more complicated and less reliable.

The description of the use case "Stock Search (Reservations)" was agreed to be valid.

In the case of use case "Stock Search (Grubby Stock)". it was agreed that (a) describes this use case. Case (b) is a separate use case: "Stock Search (Dead)". Case (c) is not a valid use case.

On the basis of the above, I think that we need to add these specific stock management functions to LCF v1.0.1, as specific use cases under 24 Retrieve (stock) item list, and make corresponding changes to the REST web service specification. We also need to ensure that codes for the selection criteria involved are added to code list SEL, if not already included.

**Comment by franciscave** [comment]
I propose to add the following to the REST web service specification, but I'm not sure about 28. Any views?

26 Retrieve list of available items at a specific location
----------------------------------------------------------

The following selects all items that are available to be borrowed (circulation-status = '03') and are at a specific location 'shelf1':

    GET http://192.168.0.99:80/lcf/1.0/items?current-location=shelf1+circulation-status=03

27 Retrieve list of loans that were overdue on a specified date
---------------------------------------------------------------

The following selects all loans that are were overdue on a specified date '2016-01-01T00:00:00':

    GET http://192.168.0.99:80/lcf/1.0/loans?end-due-date%3C2016-01-01T00:00:00

Note that each of the loans returned contains a mandatory `item-ref`, so a list of overdue items is directly derivable from a list of overdue loans.

28 Retrieve list of items that have been reserved and are in the library
--------------------------------------------------------------------

The following selects all items that have been reserved and which are in the library:

    GET http://192.168.0.99:80/lcf/1.0/items?current-location=library+reserved=true

The selection criterion `reserved=true` is true if either the item has a reservation-ref or the manifestation associated with the item has a reservation-ref.

**Comment by franciscave** [comment]
I changed the parameter separators in the HTTP query parts from '+' to '&'. I think that the latter is generally used, although RFC 3986 doesn't actually specify a parameter separator.

**Comment by franciscave** [comment]
To address the original issue I have added the words "as specified in code list SEL *[v1.0.1]*" to the Notes column in row 8 (Q02D02.2) in the LCF REST Web Service Specification..

**Comment by franciscave** [comment]
To close this issue we need to agree on the addition of Stock Management functions 26, 27 and 28. I believe that 26 and 27 are straightforward. The problem with 28 is that it involves a query in which we want to be able to say "the item is in the library and it has been reserved". It is the "and it has been reserved" bit that is problematic because I don't know how to express this in a RESTful way in the request. One could retrieve all reservation entities first, then check which of these are associated with items that are in the library. Alternatively, one could retrieve all items in the library, then check which of these have an associated reservation. The latter is more immediately useful, because one is interested in retrieving items, not reservations. But how is this to be done? Can we resolve this at today's Technical Panel meeting?

**Comment by franciscave** [comment]
At the Technical Panel Meeting on 22/09/2016 we agreed that function 26 can be added, but that the use cases for candidate functions 27 and 28 need to be more clearly defined. We agreed that the next PlugFest would provide a suitable occasion on which to attempt to come up with improved definitions that will enable us to define a clear process.

**Comment by franciscave** [comment]
Function 26 has been added to the LCF v1.0.1 specification and to the REST Web Service specification.

**Comment by franciscave** [comment]
This issue wasn't discussed at the PlugFest, so I suggest we close this for now.

**Comment by mdovey** [comment]
I think the additional SEL criteria and range mechanisms discussed in #85 will cover most if not all use cases
